name: Generate Codex Diagram

on:
  push:
    paths: # Only run if relevant code changes, not just the diagram itself
      - 'scripts/codexDiagram.ts'
      - 'folder-samples/git/**'
      - '!folder-samples/git/diagram.ai.md'
      - '.github/workflows/codex-diagram.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push the commit

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install codex
        run: pnpm add -g @openai/codex

      - name: Run codexDiagram script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
          echo "OPENAI_API_KEY: $OPENAI_API_KEY"
          node --experimental-strip-types scripts/codexDiagram.ts folder-samples/git

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: check_changes
        run: |
          git add folder-samples/git/diagram.ai.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in diagram"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git commit -m "chore: generate mermaid diagram for folder-samples/git [skip ci]"
          git push
